In [3]:
import tensorflow as tf
import numpy as np

In [17]:
np.random.seed(100)
tf.set_random_seed(100)

In [18]:
random_a = np.random.uniform(0,100,(5,5))

In [19]:
random_a

array([[54.34049418, 27.83693851, 42.45175907, 84.47761323,  0.47188562],
       [12.15691208, 67.07490847, 82.58527551, 13.67065897, 57.50933294],
       [89.13219543, 20.92021221, 18.53282196, 10.83768905, 21.96974926],
       [97.86237847, 81.16831491, 17.19410127, 81.62247487, 27.4073747 ],
       [43.17041837, 94.00298196, 81.76493788, 33.61119501, 17.54104537]])

In [20]:
random_b = np.random.uniform(0,100,(5,1))

In [21]:
random_b

array([[37.28320463],
       [ 0.56885074],
       [25.24263534],
       [79.56625085],
       [ 1.52549712]])

In [23]:
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)

In [24]:
add_op = a + b

In [25]:
mult_op = a * b

In [30]:
with tf.Session() as sess:
    add = sess.run(add_op,feed_dict={a:random_a,b:random_b})
    mult = sess.run(mult_op,feed_dict={a:random_a,b:random_b})

In [31]:
add

array([[ 91.6237  ,  65.12014 ,  79.73496 , 121.76082 ,  37.75509 ],
       [ 12.725762,  67.64375 ,  83.15412 ,  14.23951 ,  58.078186],
       [114.37483 ,  46.16285 ,  43.77546 ,  36.080326,  47.212387],
       [177.42863 , 160.73456 ,  96.76035 , 161.18872 , 106.97363 ],
       [ 44.695915,  95.52848 ,  83.290436,  35.136692,  19.066544]],
      dtype=float32)

In [32]:
mult

array([[2.0259878e+03, 1.0378502e+03, 1.5827375e+03, 3.1495962e+03,
        1.7593407e+01],
       [6.9154687e+00, 3.8155609e+01, 4.6978695e+01, 7.7765646e+00,
        3.2714230e+01],
       [2.2499314e+03, 5.2808130e+02, 4.6781726e+02, 2.7357184e+02,
        5.5457440e+02],
       [7.7865430e+03, 6.4582583e+03, 1.3680702e+03, 6.4943945e+03,
        2.1807021e+03],
       [6.5856346e+01, 1.4340128e+02, 1.2473218e+02, 5.1273781e+01,
        2.6758814e+01]], dtype=float32)